// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkf9KnTrvUShTbL2j2w37TBIfJGBSNps',
    appId: '1:151592527578:web:7868ec00c856e6f14867e3',
    messagingSenderId: '151592527578',
    projectId: 'farm-home-f6d6a',
    authDomain: 'farm-home-f6d6a.firebaseapp.com',
    storageBucket: 'farm-home-f6d6a.appspot.com',
    measurementId: 'G-WX65KBR9D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXp1P4FPr0UwpTvZnn58orCKX967pb-yI',
    appId: '1:151592527578:android:025cea9d22fb745d4867e3',
    messagingSenderId: '151592527578',
    projectId: 'farm-home-f6d6a',
    storageBucket: 'farm-home-f6d6a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkf9KnTrvUShTbL2j2w37TBIfJGBSNps',
    appId: '1:151592527578:web:b24cbfac11b536c64867e3',
    messagingSenderId: '151592527578',
    projectId: 'farm-home-f6d6a',
    authDomain: 'farm-home-f6d6a.firebaseapp.com',
    storageBucket: 'farm-home-f6d6a.appspot.com',
    measurementId: 'G-F7WE2PHZEF',
  );

}