name: Build

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.1"
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Web Build
        run: flutter build web
      - name: Android Build
        run: flutter build appbundle
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.1"
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Windows Build
        run: flutter build windows